---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: Y3VvbmduYzMwMTBwYXNzCg==
  usename: Y3VvbmduYzMwMTB1c2VyCg==
  database: Y3VvbmduYzMwMTBkYgo=
...